### ISSUE TITLE
Play Framework 2.4.0 routing, global settings and compilation error

### ISSUE THREAD

**Issue by sasajib** [Atmosphere/atmosphere-play#31]
#### Error Log
```log
overriding method onRequestReceived in trait GlobalSettings of type (request: play.api.mvc.RequestHeader)(play.api.mvc.RequestHeader, play.api.mvc.Handler); method onRequestReceived has incompatible type
```

```scala
object Global extends GlobalSettings {
    override def onStart(app: Application): Unit = {
        AtmosphereCoordinator.instance().discover(classOf[MyAtmosphereSocket]).ready()
        super.onStart(app)
    }

    override def onStop(app: Application): Unit = {
        AtmosphereCoordinator.instance().shutdown()
        super.onStop(app)
    }

    override def onRequestReceived(request: RequestHeader): Option[Handler] =
        Router.dispatch(request) match {
            case Some(result) => Some(result)
            case None => super.onRouteRequest(request)
        }


}
```
I am basically trying the [atmosphere-play-samples](https://github.com/Atmosphere/atmosphere-samples/tree/master/play-samples).

It was working in play V2.3.x...

**Comment by jfarcand** [comment]
Contribution welcomed!

**Comment by sasajib** [comment]
@jfarcand thx! happy to be here...and keep up the good work

**Comment by umbreak** [comment]
Play 2.4 moves away from GlobalSettings.Any method in onStart and onStop can be just configred as a [Guice AbstractModule](https://www.playframework.com/documentation/2.4.x/ScalaDependencyInjection#Eager-bindings).
For the method `onRequestReceived` you can create a class in the root package which implements `HttpRequestHandler` and later on [implement it](https://www.playframework.com/documentation/2.4.x/ScalaHttpRequestHandlers).

**Comment by umbreak** [comment]
If it is possible to do the stuff that's done now onStart and onStop through Guice Injection, then the migration to 2.4 is not difficult.

**Comment by jfarcand** [comment]
@umbreak First, please file an issue onlt under one project as it produces a lot of pollution. I will take care or migrating in case your are under the wrong one.

I've not time to work on `2.4` right now so your contribution is greatly appreciated. I will review and integrate your pull requests :-)

Thanks!

**Comment by BradZzz** [comment]
I am trying to get this working on play 2.4 also. It looks like 2.3 and below work just fine. Has anyone come up with a good workaround yet?

**Comment by mrafaelgomes** [comment]
has anyone found a solution for play 2.4.x?

**Comment by stegmann-idnow** [comment]
Hi,
I found a solution thats working for me.
see #34  

I tested this solution only with a play-java project with play version 2.4.6.

**Comment by jfarcand** [comment]
Released atmosphere-play `2.2.0` which is based on Atmosphere `2.3.5` . Anyone who has the cycle can upgrade to Atmosphere `2.4.2`.
